apiVersion: v1
kind: ServiceAccount
metadata:
  name: hunyuan3d-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: genai3d-sa@your-project-id.iam.gserviceaccount.com # {"description": "Replace with your GSA name and GCP project ID"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunyuan3d-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hunyuan3d
  template:
    metadata:
      annotations:
      labels:
        app: hunyuan3d
    spec:
      serviceAccountName: hunyuan3d-sa
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      volumes:
      - name: nfs-pvc-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
      containers:
      - name: hunyuan3d
        image: europe-west3-docker.pkg.dev/your-project-id/random-demos/h3d:latest
        ports:
        - containerPort: 8080
        env:
        - name: HUNYUAN3D_URL
          value: "http://localhost:8080/generate"
        - name: PROJECT_ID
          value: "your-gcp-project-id"
        - name: SUBSCRIPTION_NAME
          value: "genai3d-work-topic-sub"
        - name: LOCATION
          value: "your-gcp-location"
        readinessProbe:
          httpGet:
            path: /status/0
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 8
            memory: 32Gi
            ephemeral-storage: 10Gi
          limits:
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: nfs-pvc-volume
          mountPath: /root
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Ti # Adjust size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: /h3d_share
    server: 10.78.21.66
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # Empty storageClassName to bind to the PV without a provisioner
  resources:
    requests:
      storage: 1Ti # Must match or be less than the PV's capacity
  volumeName: nfs-pv
---
apiVersion: v1
kind: Service
metadata:
  name: hunyuan3d-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: hunyuan3d
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: genai3d-subdomain-cert
spec:
  domains:
    - genai3d.nikolaidan.demo.altostrat.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hunyuan3d-ingress
  annotations:
    networking.gke.io/managed-certificates: genai3d-subdomain-cert
spec:
  rules:
  - host: genai3d.nikolaidan.demo.altostrat.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hunyuan3d-service
            port:
              number: 80